version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TRADING_ENV=development
      - TRADING_CLAUDE_API_KEY=${CLAUDE_API_KEY}
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web